### ISSUE TITLE
Issues with sass `stack level too deep `

### ISSUE THREAD

**Issue by johanvergeer** [envygeeks/jekyll-docker#230]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [ ] I Am on Linux
- [x] I Am on macOS

## Description

I am trying to create a container to run Jekyll with the [Forty Jekyll Theme](https://github.com/andrewbanchich/forty-jekyll-theme)

When I run the container with `docker container run --rm --volume $PWD:/srv/jekyll jekyll/jekyll jekyll build` I keep getting an error. (See output below)

The thing is that when I run Jekyll with this theme locally, it works perfectly. 

## Steps

- Clone the Forty Jekyll Theme git repo
- Run the cloned project with the jekyll/jekyll Docker image

## Output

```sh
$ git clone git@github.com:andrewbanchich/forty-jekyll-theme.git
$ cd forty-jekyll-theme
$ docker container run --rm --volume $PWD:/srv/jekyll jekyll/jekyll jekyll build

Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
/usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `each': stack level too deep (SystemStackError)
	from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `map'
	from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `_perform'
	from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/node.rb:50:in `perform'
	from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/operation.rb:76:in `_perform'
	from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/node.rb:50:in `perform'
	from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:186:in `perform_arg'
	from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `block in _perform'
	from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `each'
	 ... 565 levels...
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/jekyll-3.8.3/exe/jekyll:15:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:29:in `load'
	from /usr/local/bundle/bin/jekyll:29:in `<main>'
```

## Expected

This is what the output is when I just run `jekyll serve` on my local machine:

```sh
Configuration file: /Users/johanvergeer/projects/johanvergeer-com/site/_config.yml
            Source: /Users/johanvergeer/projects/johanvergeer-com/site
       Destination: /Users/johanvergeer/projects/johanvergeer-com/site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.907 seconds.
 Auto-regeneration: enabled for '/Users/johanvergeer/projects/johanvergeer-com/site'
    Server address: http://127.0.0.1:4000//
  Server running... press ctrl-c to stop.
```

**Comment by envygeeks** [comment]
Hey @johanvergeer 

Stack level issues would always originate upstream even if it doesn’t happen locally vs. inside a container.  If you can provide a working replication I can clone I’d be happy to tell you which upstream it should be filed at, but at the end of the day the big belongs to the actual software, and very rarely maybe MuslC

**Comment by johanvergeer** [comment]
I'm not sure what you mean with with a working replication. 

When I clone the repo and run it locally it works, but when I run it in the container it doesn't. I also don't know how to get it working. 
I already tried to put all the dependencies in the Gemfile because I thought it might be a dependency version issue, but that dit not solve anything.

**Comment by fabsenet** [comment]
I had a powershell window to spare and tried to reproduce it. I am on windows/powershell and I had to change the git clone command.

my output:
```powershell
C:\test> git clone https://github.com/andrewbanchich/forty-jekyll-theme.git
Cloning into 'forty-jekyll-theme'...
remote: Counting objects: 974, done.
remote: Compressing objects: 100% (6/6), done.
Receiving objects:  95% (926/974), 2.24 MiB | 1.08 MiB/s   ed 968
Receiving objects: 100% (974/974), 2.53 MiB | 1.07 MiB/s, done.
Resolving deltas: 100% (558/558), done.
C:\test> cd forty-jekyll-theme
C:\test\forty-jekyll-theme [master ≡]> docker container run --rm --volume ${PWD}:/srv/jekyll jekyll/jekyll jekyll build
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching public_suffix 3.0.2
Installing public_suffix 3.0.2
Fetching addressable 2.5.2
Installing addressable 2.5.2
Using bundler 1.16.2
Fetching colorator 1.1.0
Installing colorator 1.1.0
Fetching concurrent-ruby 1.0.5
Installing concurrent-ruby 1.0.5
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensions
Fetching http_parser.rb 0.6.0
Installing http_parser.rb 0.6.0 with native extensions
Fetching em-websocket 0.5.1
Installing em-websocket 0.5.1
Fetching ffi 1.9.25
Installing ffi 1.9.25 with native extensions
Using forty_jekyll_theme 1.2 from source at `.`
Fetching forwardable-extended 2.6.0
Installing forwardable-extended 2.6.0
Fetching i18n 0.9.5
Installing i18n 0.9.5
Fetching rb-fsevent 0.10.3
Installing rb-fsevent 0.10.3
Fetching rb-inotify 0.9.10
Installing rb-inotify 0.9.10
Fetching sass-listen 4.0.0
Installing sass-listen 4.0.0
Fetching sass 3.5.6
Installing sass 3.5.6
Fetching jekyll-sass-converter 1.5.2
Installing jekyll-sass-converter 1.5.2
Fetching ruby_dep 1.5.0
Installing ruby_dep 1.5.0
Fetching listen 3.1.5
Installing listen 3.1.5
Fetching jekyll-watch 2.0.0
Installing jekyll-watch 2.0.0
Fetching kramdown 1.17.0
Installing kramdown 1.17.0
Fetching liquid 4.0.0
Installing liquid 4.0.0
Fetching mercenary 0.3.6
Installing mercenary 0.3.6
Fetching pathutil 0.16.1
Installing pathutil 0.16.1
Fetching rouge 3.1.1
Installing rouge 3.1.1
Fetching safe_yaml 1.0.4
Installing safe_yaml 1.0.4
Fetching jekyll 3.8.3
Installing jekyll 3.8.3
Bundle complete! 3 Gemfile dependencies, 27 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
/usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `map': stack level too deep (SystemStackError)
        from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `_perform'
        from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/node.rb:50:in `perform'
        from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/operation.rb:76:in `_perform'
        from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/node.rb:50:in `perform'
        from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:186:in `perform_arg'
        from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `block in _perform'
        from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `each'
        from /usr/local/bundle/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `each_with_index'
         ... 598 levels...
        from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /usr/local/bundle/gems/jekyll-3.8.3/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bundle/bin/jekyll:29:in `load'
        from /usr/local/bundle/bin/jekyll:29:in `<main>'
```

and using the Windows 10 Subsystem for Linux:
```powershell
C:\test\forty-jekyll-theme [master ≡]> bash
fabse@bob:/mnt/c/test/forty-jekyll-theme$ jekyll build
WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.4, ~> 0.9)
      ffi (< 2, >= 0.5.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /mnt/c/test/forty-jekyll-theme/_config.yml
            Source: /mnt/c/test/forty-jekyll-theme
       Destination: /mnt/c/test/forty-jekyll-theme/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 5.073 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

so it is at least reproducable on windows...

**Comment by envygeeks** [comment]
I'm sorry but this issue belongs upstream. Please file your issue at 

https://github.com/sass/sass
https://github.com/andrewbanchich/forty-jekyll-theme
https://github.com/jekyll/jekyll

**Comment by fabsenet** [comment]
i tried a commit before the named commit in the referenced issue and it works so I think, you really can close this issue here.

```powershell
C:\test\forty-jekyll-theme [master ≡]> git checkout a2c41000d8b00a57a42c40d6ea769d82a3f97339
C:\test\forty-jekyll-theme [(a2c4100...)]> docker container run --rm --volume ${PWD}:/srv/jekyll jekyll/jekyll jekyll build
Fetching gem metadata from https://rubygems.org/...........
Fetching public_suffix 3.0.2
Installing public_suffix 3.0.2
Fetching addressable 2.5.2
...
Fetching jekyll 3.8.3
Installing jekyll 3.8.3
Bundle complete! 3 Gemfile dependencies, 27 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 1.062 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

**Comment by johanvergeer** [comment]
@envygeeks if the issue persists, I'll contact them. 
@fabsenet thanks man.
