### ISSUE TITLE
unable to update to any version > 3.8.4

### ISSUE THREAD

**Issue by MarioCodes** [envygeeks/jekyll-docker#256]
- [x] I tried updating to the latest version
  - [x] I can't, there is an issue
  - [ ] This is about an < latest
    - [ ] I understand older versions may be unsupported
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [x] I Am on Linux
  - [x] Ubuntu
  - [ ] Fedora
  - [ ] CentOS
  - [ ] Redhat
  - [ ] Debian
- [ ] I am on macOS 10.13
- [ ] I am on macOS 10.14
- [x] I'm on Docker
  - [x] I understand Docker may be unsupported

## Description

I'm building a docker-compose script with a DockerFile service, which works for versions <= 3.8.4 but at the moment I try to update it to stable or latest (or any version > 3.8.4) it breaks, without any additional change on my part.  

By breaking, I mean Jekyll is not able to Build nor Serve anymore. 

## Steps

DockerFile
~~~ sh  
# Beware when upgrading the base image. Upgrading to >= 3.8.5 breaks my config and the new one does not compile. Jekyll does not build nor serve.
FROM jekyll/jekyll:3.8.5

# Set all relative paths from now on to part from this one.
WORKDIR /srv/jekyll

# Open port
EXPOSE 4000

# Copy all the contents from the actual folder to the previously set relative path
#       --chown option is to fix a Jekyll's bug. When not set, jekyll cannot open / write the GemFile
COPY --chown=jekyll:jekyll . .

# Installs into the system, all specified Gems at GemFile
RUN bundle install 

# When everything's ready, execute this command
CMD ["bundle", "exec", "jekyll", "serve", "--trace"]
~~~

docker-compose.yml
~~~yml
version: '3.7'
services:
        website:
                build:
                        context: ./website
                        dockerfile: ./DockerFile
                image: website
                container_name: website
                ports:
                        - 4000:4000
~~~

start command
~~~ bash
docker-compose up --build
~~~

GemFile
~~~ ruby
source "https://rubygems.org"
ruby RUBY_VERSION

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "3.8.4"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
    gem "jekyll-paginate", "~> 1.1.0"
    gem 'listen', '~> 3.0'
    gem 'jekyll-sitemap'
    gem 'public_suffix', '~> 3.0.3'
    gem 'addressable', '~> 2.5.2'
    gem 'concurrent-ruby', '~> 1.0.5'
    gem 'rake'
    gem 'ffi', :platforms => :ruby
    gem 'json', '2.0.2'
end
~~~

1.- Set everything up, using version :latest or >:3.8.4
2.- docker-compose up --build

## Output

Full StackTrace
```sh
Building website
Step 1/6 : FROM jekyll/jekyll:latest
 ---> 2754bfa01869
Step 2/6 : WORKDIR /srv/jekyll
 ---> Running in dd81b698c392
Removing intermediate container dd81b698c392
 ---> 547cd0e216f3
Step 3/6 : EXPOSE 4000
 ---> Running in df4cf44eebe3
Removing intermediate container df4cf44eebe3
 ---> 121b8be1f238
Step 4/6 : COPY --chown=jekyll:jekyll . .
 ---> 622b8ea5662c
Step 5/6 : RUN bundle install
 ---> Running in 914985557d5b
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching rake 13.0.0
Installing rake 13.0.0
Fetching public_suffix 3.0.3
Installing public_suffix 3.0.3
Fetching addressable 2.5.2
Installing addressable 2.5.2
Using bundler 2.0.2
Fetching colorator 1.1.0
Installing colorator 1.1.0
Fetching concurrent-ruby 1.0.5
Installing concurrent-ruby 1.0.5
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensions
Fetching http_parser.rb 0.6.0
Installing http_parser.rb 0.6.0 with native extensions
Fetching em-websocket 0.5.1
Installing em-websocket 0.5.1
Fetching ffi 1.11.1
Installing ffi 1.11.1 with native extensions
Fetching forwardable-extended 2.6.0
Installing forwardable-extended 2.6.0
Fetching i18n 0.9.5
Installing i18n 0.9.5
Fetching rb-fsevent 0.10.3
Installing rb-fsevent 0.10.3
Fetching rb-inotify 0.10.0
Installing rb-inotify 0.10.0
Fetching sass-listen 4.0.0
Installing sass-listen 4.0.0
Fetching sass 3.7.4
Installing sass 3.7.4
Fetching jekyll-sass-converter 1.5.2
Installing jekyll-sass-converter 1.5.2
Fetching listen 3.2.0
Installing listen 3.2.0
Fetching jekyll-watch 2.2.1
Installing jekyll-watch 2.2.1
Fetching kramdown 1.17.0
Installing kramdown 1.17.0
Fetching liquid 4.0.3
Installing liquid 4.0.3
Fetching mercenary 0.3.6
Installing mercenary 0.3.6
Fetching pathutil 0.16.2
Installing pathutil 0.16.2
Fetching rouge 3.12.0
Installing rouge 3.12.0
Fetching safe_yaml 1.0.5
Installing safe_yaml 1.0.5
Fetching jekyll 3.8.4
Installing jekyll 3.8.4
Fetching jekyll-paginate 1.1.0
Installing jekyll-paginate 1.1.0
Fetching jekyll-sitemap 1.3.1
Installing jekyll-sitemap 1.3.1
Fetching json 2.0.2
Installing json 2.0.2 with native extensions
Bundle complete! 10 Gemfile dependencies, 29 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
Removing intermediate container 914985557d5b
 ---> ae44b7e9e3e7
Step 6/6 : CMD ["bundle", "exec", "jekyll", "serve", "--trace"]
 ---> Running in f215c70cdf06
Removing intermediate container f215c70cdf06
 ---> 07e89e6bff8d

Successfully built 07e89e6bff8d
Successfully tagged website:latest
Recreating website ... done
Attaching to website
website    | Configuration file: /srv/jekyll/_config.yml
website    | bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
website    | SyntaxError: /srv/jekyll/_plugins/generate_categories.rb:50: else without rescue is useless
website    | ...L = "" if (BASEURL == nil) else BASEURL
website    | ...                           ^~~~
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/external.rb:58:in `require'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/external.rb:58:in `block in require_with_graceful_fail'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/external.rb:55:in `each'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/external.rb:55:in `require_with_graceful_fail'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/plugin_manager.rb:87:in `block in require_plugin_files'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/plugin_manager.rb:85:in `each'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/plugin_manager.rb:85:in `require_plugin_files'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/plugin_manager.rb:21:in `conscientious_require'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/site.rb:114:in `setup'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/site.rb:32:in `initialize'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:30:in `new'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:30:in `process'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/commands/serve.rb:93:in `block in start'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/commands/serve.rb:93:in `each'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/commands/serve.rb:93:in `start'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
website    |   /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
website    |   /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
website    |   /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
website    |   /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
website    |   /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
website    |   /usr/local/bundle/gems/jekyll-3.8.4/exe/jekyll:15:in `<top (required)>'
website    |   /usr/local/bundle/bin/jekyll:29:in `load'
website    |   /usr/local/bundle/bin/jekyll:29:in `<top (required)>'
website exited with code 1
```

## Expected

To be able to upgrade to the last version.
For it to work just the same as with versions <= 3.8.4.  
If I change the DockerFile version and repeat exactly the same steps, it works.

**Comment by envygeeks** [comment]
Hi @MarioCodes, this is a problem with your plugin `generate_categories`, not a problem with Jekyll-Docker, it looks like you are doing something funky with an if statement, this is out of the scope of Jekyll-Docker, as any syntax errors would belong to the author of said syntax.

**Comment by MarioCodes** [comment]
Hi @envygeeks, I just find it very weird, because the first problem there is:  
~~~
website    | bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
~~~
looking on the web, there're a lot of such problems and none had to do with syntax. Aside from this, it just works perfectly on most versions <= 3.8.4 but stops working on > 3.8.5 (and stable).

**Comment by envygeeks** [comment]
Indeed, I can see why that would be confusing... however, that's the Ruby interpreter telling you that `jekyll` failed to load because of of an error in a file that was required by `jekyll`, the following error is what actually happened:

```
website    | SyntaxError: /srv/jekyll/_plugins/generate_categories.rb:50: else without rescue is useless
website    | ...L = "" if (BASEURL == nil) else BASEURL
```

**Comment by MarioCodes** [comment]
Got it. Thanks for the help. 
I'll try to solve it again then.
