### ISSUE TITLE
Bundler: Fetching source index from https://rubygems.org/

### ISSUE THREAD

**Issue by mik0s** [envygeeks/jekyll-docker#262]
I try to create a site, but I get an error.

```
[root@cp jekyll]# export JEKYLL_VERSION=3.8
[root@cp jekyll]# docker run --rm --volume="$PWD:/srv/jekyll" -it jekyll/jekyll:$JEKYLL_VERSION jekyll new test3
Unable to find image 'jekyll/jekyll:3.8' locally
3.8: Pulling from jekyll/jekyll
9d48c3bd43c5: Already exists
9ce9598067e7: Already exists
278f4c997324: Already exists
bfca09e5fd9a: Already exists
2612f15b9d22: Already exists
322c093d5418: Pull complete
Digest: sha256:9521c8aae4739fcbc7137ead19f91841b833d671542f13e91ca40280e88d6e34
Status: Downloaded newer image for jekyll/jekyll:3.8
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux-musl]
Running bundle install in /srv/jekyll/test3...
  Bundler: Fetching source index from https://rubygems.org/Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
  Bundler: Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
  Bundler: Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
  Bundler: Could not fetch specs from https://rubygems.org/

```

I try to create a site, but I get an error.
I tried different versions - none of them work.
But files appear in the site’s directory, but probably not all.

```
[root@cp jekyll]# ls /srv/jekyll/test3/
404.html  about.md  _config.yml  Gemfile  index.md  _posts
```

Also, the site is not built

```
[root@cp jekyll]# cd /srv/jekyll/test3/
[root@cp test3]# docker run --rm --volume="$PWD:/srv/jekyll" -it jekyll/jekyll:$JEKYLL_VERSION jekyll build
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux-musl]
Traceback (most recent call last):
	15: from /usr/gem/bin/jekyll:23:in `<main>'
	14: from /usr/gem/bin/jekyll:23:in `load'
	13: from /usr/gem/gems/jekyll-3.8.6/exe/jekyll:11:in `<top (required)>'
	12: from /usr/gem/gems/jekyll-3.8.6/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler.rb:107:in `setup'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:20:in `setup'
	 9: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:108:in `block in definition_method'
	 8: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/definition.rb:226:in `requested_specs'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/definition.rb:237:in `specs_for'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/definition.rb:170:in `specs'
	 5: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/definition.rb:258:in `resolve'
	 4: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/resolver.rb:22:in `resolve'
	 3: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/resolver.rb:49:in `start'
	 2: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/resolver.rb:255:in `verify_gemfile_dependencies_are_found!'
	 1: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/resolver.rb:255:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'minima (~> 2.0)' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
```

Am I doing something wrong?

**Comment by envygeeks** [comment]
Networking issues always originate from the system that hosts docker unless you severely misconfigure Docker and it's networking stack (for most people this will never be the case.)

**Comment by mik0s** [comment]
what to look at? I didn’t set anything up specifically.

**Comment by envygeeks** [comment]
You'll need to look at your systems networking.  Sorry I don't have with these kinds of issues!
