### ISSUE TITLE
Site build fails since its missing v8

### ISSUE THREAD

**Issue by reubensjohn** [envygeeks/jekyll-docker#283]
Looks like this is a problem with alpine, since it does not have v8.

See the stack trace below,
```
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux-musl]
Traceback (most recent call last):
        16: from /usr/local/bundle/bin/jekyll:29:in `<main>'
        15: from /usr/local/bundle/bin/jekyll:29:in `load'
        14: from /usr/local/bundle/gems/jekyll-3.8.7/exe/jekyll:11:in `<top (required)>'
        13: from /usr/local/bundle/gems/jekyll-3.8.7/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
        12: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler.rb:114:in `require'
        11: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
        10: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
         9: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
         8: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
         7: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
         6: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `require'
         5: from /usr/local/bundle/gems/jekyll-lunr-js-search-3.3.0/lib/jekyll-lunr-js-search.rb:2:in `<top (required)>'
         4: from /usr/local/bundle/gems/jekyll-lunr-js-search-3.3.0/lib/jekyll-lunr-js-search.rb:2:in `require'
         3: from /usr/local/bundle/gems/jekyll-lunr-js-search-3.3.0/lib/jekyll_lunr_js_search/indexer.rb:5:in `<top (required)>'
         2: from /usr/local/bundle/gems/jekyll-lunr-js-search-3.3.0/lib/jekyll_lunr_js_search/indexer.rb:5:in `require'
         1: from /usr/local/bundle/gems/therubyracer-0.12.3/lib/v8.rb:4:in `<top (required)>'
/usr/local/bundle/gems/therubyracer-0.12.3/lib/v8.rb:4:in `require': Error relocating /usr/local/bundle/gems/therubyracer-0.12.3/lib/v8/init.so: __vfprintf_chk: symbol not found - /usr/local/bundle/gems/therubyracer-0.12.3/lib/v8/init.so (LoadError)
```

**Comment by envygeeks** [comment]
Is there a bug here?

**Comment by reubensjohn** [comment]
Not really, I can build my site on my mac, but inside docker the build fails.

I also see this in the documentation

> You can install system packages by providing a file named .apk with one package per line.

I could try installing v8 myself. How do I pass this file to the docker container?

**Comment by envygeeks** [comment]
If it's included inside of your Jekyll Root we'll pick it up! On a side note there is a plan to migrate to Ubuntu eventually sometime soon, but I have to do it in a way that doesn't affect people so harshly because a lot of enterprise users rely on this image.

**Comment by envygeeks** [comment]
This should be fixed by the new image work.
